# ============================================================
#  RocketCom Top-level Makefile
#  Usage:
#    make            — compile only
#    make flash      — compile + upload via ST-Link
#    make monitor    — open serial monitor, auto-detect port (Ctrl+A K to quit)
#    make all        — compile + flash + monitor
#    make host-test  — run all host unit tests (no board needed)
#    make clean      — remove build artifacts
# ============================================================

# ---- Toolchain (STM32CubeIDE built-in, must NOT use Homebrew version) ----
CUBEIDE_PLUGINS := /Applications/STM32CubeIDE.app/Contents/Eclipse/plugins
GCC_PATH        := $(shell ls -d $(CUBEIDE_PLUGINS)/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.*/tools/bin 2>/dev/null | sort -V | tail -1)
CUBEPROG        := $(shell ls $(CUBEIDE_PLUGINS)/com.st.stm32cube.ide.mcu.externaltools.cubeprogrammer.*/tools/bin/STM32_Programmer_CLI 2>/dev/null | sort -V | tail -1)

# ---- Project paths ----
BUILD_DIR  := firmware/main_flight_code/Debug
ELF        := $(BUILD_DIR)/Main_AV_F407.elf
BACKUP_ELF := $(BUILD_DIR)/Main_AV_F407_backup.elf
GROUND_ELF := $(BUILD_DIR)/Main_AV_F407_ground.elf
BOARD_CFG  := firmware/main_flight_code/Core/Inc/board_config.h

# ---- 版本標頭（開機橫幅顯示 git 版次 + 建置時間；語意化版號在 board_config.h::FIRMWARE_VERSION）----
VERSION_HDR := firmware/main_flight_code/Core/Inc/build_version.h
FW_GIT      := $(shell git -C "$(CURDIR)" describe --tags --always --dirty 2>/dev/null || echo nogit)
FW_BUILD    := $(shell date '+%Y-%m-%d_%H:%M:%S')

# ---- Serial monitor ----
# PORT 留空 = 自動偵測 USB 序列埠；可用 `make monitor PORT=/dev/cu.xxx` 手動覆寫
PORT      :=
BAUD      := 460800

# ============================================================

.PHONY: build build-primary build-backup build-ground flash flash-primary flash-backup flash-ground flash-primary-only flash-ground-only monitor all clean host-test gen-version

## 產生版本標頭（git 版次 + 建置時間），供開機橫幅顯示；每次建置前自動更新。
gen-version:
	@printf '/* AUTO-GENERATED by Makefile — 勿手改 */\n#ifndef BUILD_VERSION_H\n#define BUILD_VERSION_H\n#define FW_GIT   "%s"\n#define FW_BUILD "%s"\n#endif\n' '$(FW_GIT)' '$(FW_BUILD)' > "$(VERSION_HDR)"
	@echo "[version] FW_GIT=$(FW_GIT)  FW_BUILD=$(FW_BUILD)"

## Default target: compile only
build: gen-version
	@test -n "$(GCC_PATH)" || (echo "[ERROR] STM32CubeIDE 工具鏈未找到，請確認已安裝 STM32CubeIDE"; exit 1)
	export PATH="$(GCC_PATH):$$PATH" && \
	$(MAKE) -C $(BUILD_DIR) all

## Alias so bare `make` also compiles
default: build

## Upload .elf to MCU via ST-Link SWD
flash: build
	@test -n "$(CUBEPROG)" || (echo "[ERROR] STM32_Programmer_CLI 未找到，請確認已安裝 STM32CubeIDE"; exit 1)
	"$(CUBEPROG)" -c port=SWD -w "$(CURDIR)/$(ELF)" -rst

## 編譯主航電（BOARD_ROLE=ROLE_PRIMARY）
build-primary: gen-version
	@test -n "$(GCC_PATH)" || (echo "STM32CubeIDE 工具鏈未找到，請確認已安裝 STM32CubeIDE"; exit 1)
	@sed -i '' 's|ROLE_[A-Z]*   /\* MAKE_ROLE_LINE|ROLE_PRIMARY   /* MAKE_ROLE_LINE|' "$(BOARD_CFG)"
	@echo "[build-primary] BOARD_ROLE = ROLE_PRIMARY"
	@export PATH="$(GCC_PATH):$$PATH" && $(MAKE) -C $(BUILD_DIR) all; STATUS=$$?; \
	  sed -i '' 's|ROLE_[A-Z]*   /\* MAKE_ROLE_LINE|ROLE_PRIMARY   /* MAKE_ROLE_LINE|' "$(BOARD_CFG)"; touch "$(BOARD_CFG)"; \
	  if [ $$STATUS -ne 0 ]; then echo "[build-primary] 建置失敗"; exit $$STATUS; fi

## 燒錄主航電 binary
flash-primary: build-primary
	@test -n "$(CUBEPROG)" || (echo "STM32_Programmer_CLI 未找到，請確認已安裝 STM32CubeIDE"; exit 1)
	"$(CUBEPROG)" -c port=SWD mode=UR -w "$(CURDIR)/$(ELF)" -rst

## 編譯備援航電（BOARD_ROLE=ROLE_BACKUP）
build-backup: gen-version
	@test -n "$(GCC_PATH)" || (echo "STM32CubeIDE 工具鏈未找到，請確認已安裝 STM32CubeIDE"; exit 1)
	@sed -i '' 's|ROLE_[A-Z]*   /\* MAKE_ROLE_LINE|ROLE_BACKUP   /* MAKE_ROLE_LINE|' "$(BOARD_CFG)"
	@echo "[build-backup] BOARD_ROLE = ROLE_BACKUP"
	@export PATH="$(GCC_PATH):$$PATH" && $(MAKE) -C $(BUILD_DIR) all; STATUS=$$?; \
	  sed -i '' 's|ROLE_[A-Z]*   /\* MAKE_ROLE_LINE|ROLE_PRIMARY   /* MAKE_ROLE_LINE|' "$(BOARD_CFG)"; touch "$(BOARD_CFG)"; \
	  if [ $$STATUS -ne 0 ]; then echo "[build-backup] 建置失敗"; exit $$STATUS; fi
	@cp "$(ELF)" "$(BACKUP_ELF)" && echo "[build-backup] -> $(BACKUP_ELF)"

## 燒錄備援航電 binary（會先 build-backup）
flash-backup: build-backup
	@test -n "$(CUBEPROG)" || (echo "STM32_Programmer_CLI 未找到，請確認已安裝 STM32CubeIDE"; exit 1)
	"$(CUBEPROG)" -c port=SWD mode=UR -w "$(CURDIR)/$(BACKUP_ELF)" -rst

## 編譯地面站（BOARD_ROLE=ROLE_GROUND）
build-ground: gen-version
	@test -n "$(GCC_PATH)" || (echo "STM32CubeIDE 工具鏈未找到，請確認已安裝 STM32CubeIDE"; exit 1)
	@sed -i '' 's|ROLE_[A-Z]*   /\* MAKE_ROLE_LINE|ROLE_GROUND   /* MAKE_ROLE_LINE|' "$(BOARD_CFG)"
	@echo "[build-ground] BOARD_ROLE = ROLE_GROUND"
	@export PATH="$(GCC_PATH):$$PATH" && $(MAKE) -C $(BUILD_DIR) all; STATUS=$$?; \
	  sed -i '' 's|ROLE_[A-Z]*   /\* MAKE_ROLE_LINE|ROLE_PRIMARY   /* MAKE_ROLE_LINE|' "$(BOARD_CFG)"; touch "$(BOARD_CFG)"; \
	  if [ $$STATUS -ne 0 ]; then echo "[build-ground] 建置失敗"; exit $$STATUS; fi
	@cp "$(ELF)" "$(GROUND_ELF)" && echo "[build-ground] -> $(GROUND_ELF)"

## 燒錄地面站 binary（會先 build-ground）
flash-ground: build-ground
	@test -n "$(CUBEPROG)" || (echo "STM32_Programmer_CLI 未找到，請確認已安裝 STM32CubeIDE"; exit 1)
	"$(CUBEPROG)" -c port=SWD mode=UR -w "$(CURDIR)/$(GROUND_ELF)" -rst

## 僅燒錄主航電 binary（不重新編譯，直接燒錄現有 ELF）
flash-primary-only:
	@test -n "$(CUBEPROG)" || (echo "STM32_Programmer_CLI 未找到，請確認已安裝 STM32CubeIDE"; exit 1)
	"$(CUBEPROG)" -c port=SWD mode=UR -w "$(CURDIR)/$(ELF)" -rst

## 僅燒錄地面站 binary（不重新編譯，直接燒錄現有 ELF）
flash-ground-only:
	@test -n "$(CUBEPROG)" || (echo "STM32_Programmer_CLI 未找到，請確認已安裝 STM32CubeIDE"; exit 1)
	"$(CUBEPROG)" -c port=SWD mode=UR -w "$(CURDIR)/$(GROUND_ELF)" -rst


## Open serial monitor (auto-detect USB serial port; quit with Ctrl+A then K)
## 自動偵測序列埠（FTDI/CP210x/CH340/CDC）；可用 `make monitor PORT=/dev/cu.xxx` 覆寫
monitor:
	@PORT="$(PORT)"; \
	if [ -z "$$PORT" ]; then \
	  for p in /dev/cu.usbserial-* /dev/cu.SLAB_USBtoUART* /dev/cu.wchusbserial* /dev/cu.usbmodem*; do \
	    [ -e "$$p" ] && { PORT="$$p"; break; }; \
	  done; \
	fi; \
	if [ -z "$$PORT" ]; then \
	  echo "[ERROR] 找不到序列埠。請插上 USB-TTL，或手動指定：make monitor PORT=/dev/cu.xxx"; \
	  echo "        目前可用的 /dev/cu.* 裝置："; \
	  ls /dev/cu.* 2>/dev/null | sed 's/^/          /' || echo "          （無）"; \
	  exit 1; \
	fi; \
	echo "[monitor] $$PORT @ $(BAUD)（離開：先按 Ctrl+A 再按 K）"; \
	exec screen "$$PORT" $(BAUD)

## Compile + flash + monitor
all: flash monitor

## Run all host unit tests (pure-logic headers, no HAL / board needed)
host-test:
	$(MAKE) -C tests run

## Remove build artifacts
clean:
	$(MAKE) -C $(BUILD_DIR) clean
	$(MAKE) -C tests clean
